import "./globals.css";
import ReactQueryProvider from "@/components/Providers/ReactQueryProvider";
import NavBar from "@/components/Nav/NavBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <NavBar />
      <body className="bg-white">
        <div className="container">
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </div>
      </body>
    </html>
  );
}
