# Generated by Django 5.0.6 on 2024-06-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockdata",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
