# Generated by Django 5.0.6 on 2024-06-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_stockdata_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockdata",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
